--------------------------------------------------------
--  DDL for Table SM_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "SM_USER_ROLE" 
   (  "ID" NUMBER, 
  "USER_ID" NUMBER, 
  "ROLE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SM_USER_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SM_USER_ROLE_PK" ON "SM_USER_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger SM_USER_ROLE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SM_USER_ROLE_TRG" 
BEFORE INSERT ON SM_USER_ROLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SM_USER_ROLE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SM_USER_ROLE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table SM_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "SM_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SM_USER_ROLE" ADD CONSTRAINT "SM_USER_ROLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SM_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SM_USER_ROLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SM_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "SM_USER_ROLE" ADD CONSTRAINT "SM_USER_ROLE_ROLE_FK" FOREIGN KEY ("ROLE_ID")
    REFERENCES "SM_ROLE" ("ID") ENABLE;
  ALTER TABLE "SM_USER_ROLE" ADD CONSTRAINT "SM_USER_ROLE_USER_FK" FOREIGN KEY ("USER_ID")
    REFERENCES "SM_USER" ("USER_ID") ENABLE;

REM INSERTING into SM_USER_ROLE
SET DEFINE OFF;
Insert into SM_USER_ROLE (ID,USER_ID,ROLE_ID) values (1,4,3);
Insert into SM_USER_ROLE (ID,USER_ID,ROLE_ID) values (2,5,5);
Insert into SM_USER_ROLE (ID,USER_ID,ROLE_ID) values (3,8,4);
Insert into SM_USER_ROLE (ID,USER_ID,ROLE_ID) values (4,9,4);

Commit;