--------------------------------------------------------
--  DDL for Table SM_USER
--------------------------------------------------------

  CREATE TABLE "SM_USER" 
   (  "USER_ID" NUMBER(10,0), 
  "FIRST_NAME" VARCHAR2(30 BYTE), 
  "SECOND_NAME" VARCHAR2(30 BYTE), 
  "THIRD_NAME" VARCHAR2(30 BYTE), 
  "LAST_NAME" VARCHAR2(30 BYTE), 
  "DATE_OF_BIRTH" DATE, 
  "DATE_OF_DEATH" DATE, 
  "GENDER" VARCHAR2(1 BYTE), 
  "RACE" VARCHAR2(2 BYTE), 
  "PROFILE_PHOTO_PATH" VARCHAR2(100 BYTE), 
  "USERNAME" VARCHAR2(50 BYTE), 
  "PASSWORD" VARCHAR2(20 BYTE), 
  "SSN" VARCHAR2(10 BYTE), 
  "ACCOUNT_STATUS" VARCHAR2(1 BYTE) DEFAULT 'A', 
  "DATE_LAST_LOGON" TIMESTAMP (6), 
  "TIMES_LOGON" NUMBER, 
  "USER_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SM_USER"."USER_CODE" IS 'like student code, Employee Number .. etc.';
--------------------------------------------------------
--  DDL for Index SM_User_pk
--------------------------------------------------------

  CREATE UNIQUE INDEX "SM_User_pk" ON "SM_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger SM_User_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SM_User_TRG" 
BEFORE INSERT ON "SM_USER" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SM_User_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SM_USER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SM_USER_TRG" 
BEFORE INSERT ON "SM_USER" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SM_USER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SM_User_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SM_User_TRG1" 
BEFORE INSERT ON "SM_USER" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SM_User_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table SM_USER
--------------------------------------------------------

  ALTER TABLE "SM_USER" ADD CONSTRAINT "SM_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SM_USER" MODIFY ("ACCOUNT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SM_USER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SM_USER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SM_USER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SM_USER" MODIFY ("USER_ID" NOT NULL ENABLE);

REM INSERTING into SM_USER
SET DEFINE OFF;
Insert into SM_USER (USER_ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,LAST_NAME,DATE_OF_BIRTH,DATE_OF_DEATH,GENDER,RACE,PROFILE_PHOTO_PATH,USERNAME,PASSWORD,SSN,ACCOUNT_STATUS,DATE_LAST_LOGON,TIMES_LOGON,USER_CODE) values (1,'John',null,null,'Smith',to_date('15-JUN-87','DD-MON-RR'),null,'M','W','/files/photos/1234/profile.jpg','jsmith','welcome!','322417226','A',null,null,null);
Insert into SM_USER (USER_ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,LAST_NAME,DATE_OF_BIRTH,DATE_OF_DEATH,GENDER,RACE,PROFILE_PHOTO_PATH,USERNAME,PASSWORD,SSN,ACCOUNT_STATUS,DATE_LAST_LOGON,TIMES_LOGON,USER_CODE) values (4,'Jill',null,null,'McKarthy',to_date('12-MAR-77','DD-MON-RR'),null,'F','W','/files/photos/3324/profile.jpg','jmckarthy','hello123','410351234','A',null,null,null);
Insert into SM_USER (USER_ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,LAST_NAME,DATE_OF_BIRTH,DATE_OF_DEATH,GENDER,RACE,PROFILE_PHOTO_PATH,USERNAME,PASSWORD,SSN,ACCOUNT_STATUS,DATE_LAST_LOGON,TIMES_LOGON,USER_CODE) values (5,'James',null,null,'Williams',to_date('28-AUG-82','DD-MON-RR'),null,'M','B','/files/photos/4455/profile.jpg',null,null,null,'A',null,null,null);
Insert into SM_USER (USER_ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,LAST_NAME,DATE_OF_BIRTH,DATE_OF_DEATH,GENDER,RACE,PROFILE_PHOTO_PATH,USERNAME,PASSWORD,SSN,ACCOUNT_STATUS,DATE_LAST_LOGON,TIMES_LOGON,USER_CODE) values (8,'Donna',null,null,'Williams',to_date('12-MAY-15','DD-MON-RR'),null,'F','B','/files/photos/1337/profile.jpg',null,null,null,'A',null,null,null);
Insert into SM_USER (USER_ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,LAST_NAME,DATE_OF_BIRTH,DATE_OF_DEATH,GENDER,RACE,PROFILE_PHOTO_PATH,USERNAME,PASSWORD,SSN,ACCOUNT_STATUS,DATE_LAST_LOGON,TIMES_LOGON,USER_CODE) values (9,'Noah',null,null,'Williams',to_date('01-JUN-15','DD-MON-RR'),null,'M',null,'/files/photos/6513/profile.jpg',null,null,null,'A',null,null,null);
Insert into SM_USER (USER_ID,FIRST_NAME,SECOND_NAME,THIRD_NAME,LAST_NAME,DATE_OF_BIRTH,DATE_OF_DEATH,GENDER,RACE,PROFILE_PHOTO_PATH,USERNAME,PASSWORD,SSN,ACCOUNT_STATUS,DATE_LAST_LOGON,TIMES_LOGON,USER_CODE) values (10,'Emma',null,null,'Williams',to_date('05-NOV-13','DD-MON-RR'),null,'F',null,null,null,null,null,'A',null,null,null);
